### ISSUE TITLE
Cross-references issues

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/odoc#42]
There are still a few problems with cross references (`{{!U.id}text}` ocamldoc syntax).

1. It seems that you cannot refer to yourself in a compilation unit `U` which the `ocamldoc` language allows (i.e. references of the form `{{!U.id}text}`) in the doc strings of `U` itself). Not sure whether this was a good  idea in the first place though. (E.g. in ocamldoc the second `Ptime` in [this](http://docs.mirage.io/ptime/Ptime/index.html) module preamble links to iteself, not very useful in this case though).
2. References to other compilation units that a unit formally doesn't depend on are not resolved 
(e.g. `Ptime_clock` in [this](http://docs.mirage.io/ptime/Ptime/index.html) module preamble). This concerns intra and inter package references.
2. In ocamldoc `{!U.id}` resolution first looks for a module specification `U.id` and then for a documentation section `id` anchor. It seems to be the converse in `odoc` (see [this reference](http://docs.mirage.io/astring/Astring/index.html#val-(^)), [src](https://github.com/dbuenzli/astring/blob/842a4bc7c7a28bdc1c412d01bf7f3441c3758d31/src/astring.mli#L24-L25), [target](https://github.com/dbuenzli/astring/blob/842a4bc7c7a28bdc1c412d01bf7f3441c3758d31/src/astring.mli#L242-L249))
3. When a reference  `{{!U.id}text}` is unresolved, `U.id` is spliced in. `text` should instead, `span`ned  with a `xref-unresolved` class so that I can be made visible through CSS. Adding a `title` attribute to the span with the text `unresolved $id` allows to show the unresolved reference in a tool tip.

**Comment by dbuenzli** [comment]
W.r.t. to self reference, the problem is that what `ocamldoc` does is ambiguous. Here's a concrete example. The `S.Make` here: 

http://docs.mirage.io/react/React/S/index.html#module-type-EqType
http://erratique.ch/software/react/doc/React.S.html#special

I corrected this the `react` sources https://github.com/dbuenzli/react/commit/426e44451d81a7b4fe18806dfd9238ed0071fede

**Comment by trefis** [comment]
I just noticed one disturbing self reference in ocamlary. Have a look at the preamble of the `Buffer` module.
The reference should link to `Buffer.t` in the stdlib (at least, I believe this is the intent) but gets only partially resolved to the `Buffer` module being defined.

**Comment by dbuenzli** [comment]
Indeed. Can't you lookup the different scopes and take the first one that resolves or what about warning on unambiguous self-references to deprecate them and never resolve them (i.e. always link to the stdlib `Buffer` above) ?

It is a bit strange to have the doc language behave differently from the language's scoping rule (though in practice this is already the case because of mutual references between modules in the docs without them being made recursive modules).

**Comment by dbuenzli** [comment]
> 2. References to other compilation units that a unit formally doesn't depend on are not resolved
>     (e.g. `Ptime_clock` in [this](http://docs.mirage.io/ptime/Ptime/index.html) module preamble). This concerns intra and inter package references.

Just to note that it seems no progress has been made on this front and is the source of some of the disturbing red links and (sometimes not red like [this reference](https://b0-system.github.io/odig/doc/ptime/Ptime/index.html) to `Ptime_clock` because of #333)  that can be spotted in the best-effort docset [published](https://b0-system.github.io/odig/doc/) by `odig`. 

Also I guess solving this will entail a change in the format spitted out by `html-deps` (concrete compilation unit hashes are spitted out the moment, but if the compilation unit you refer to is only in a comment you won't have that information).

**Comment by lpw25** [comment]
> Also I guess solving this will entail a change in the format spitted out by html-deps

The plan is for html-deps to display dependencies at the package rather than unit level. This is so that we can handle things like canonical redirections properly. We also intend to extend the reference syntax to allow you to specify the package, which will allow you to make references to packages that you do not depend on.

**Comment by Julow** [comment]
Point 1 and 4 are now resolved (thought, no tooltip for unresolved references).

The `link` phase solves the point 2 but the driver has to be aware of the dependency. It's reasonnable for a driver to assume that linking a module depends on all modules in the same package and in transitive dependencies to be compiled.
References to packages that are not dependencies is not implemented in a driver I'm aware of.
The `Ptime_clock` link is as expected on https://ocaml.org/p/ptime/latest/doc/index.html

Point 3 is what's currently implemented:

```ocaml
module U : sig
  (** *)

  (** {0:append Append} *)

  val append : string -> string -> string

end

(** Point to the section: {!U.append} *)
```

**Comment by Julow** [comment]
Fixed in https://github.com/ocaml/odoc/pull/945
